openapi: 3.0.0
info:
  title: API d'Onboarding pour les étudiants
  description: STD22069
  version: 1.3.0
servers:
  - url: http://std22069.com
paths:
  /students:
    get:
      summary: Récupérer les informations des étudiants
      responses:
        '200':
          description: Succès - Liste des étudiants récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    birthdate:
                      type: string
                      format: date
                  example:
                    - id: 1
                      name: Sanda
                      birthdate: '2003-07-15'
                    
        '500':
          description: server error
    post:
      summary: Ajouter un nouvel étudiant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                birthdate:
                  type: string
                  format: date
              required:
                - name
                - birthdate
            example:
              name: NouveauNom
              birthdate: '2000-01-01'
      responses:
        '200':
          description: Succès - Étudiant ajouté avec succès
          content:
            application/json:
              example:
                message: Étudiant ajouté avec succès
        '500':
          description: server error
